### ISSUE TITLE
doesn't load in firefox

### ISSUE THREAD

**Issue by pvh** [pvh/blutack#11]
had to set a config value to allow for "insecure handoff". probably a sync-server config issue but not sure yet.

network.websocket.allowInsecureFromHTTPS

detalis: https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue

**Comment by paulsonnentag** [comment]
I think in general we should add ssl certificates, on android I have the same problem. I fixed the issue with the shared worker but it still doesn't work because of the unencrypted websocket connection.

**Comment by paulsonnentag** [comment]
Works now thanks to the ssl certificate
